# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Unittest
    env:
      IMS_TOKEN: ${{ secrets.IMS_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v5

    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install requirements and setup tools
      run: >-
        # Upgrade pip
        python -m pip install --upgrade pip
        # Install build deps
        python -m pip install setuptools wheel

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4

    - name: Update version in setup.py
      run: >-
        sed -i "s/{{VERSION_PLACEHOLDER}}/0.0.1/g" setup.py

    - name: Build
      run: >-
        python setup.py install

    - uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Asia/Jerusalem"
        timezoneMacos: "Asia/Jerusalem"

    # Tests with unittest
    - name: Run UnitTests
      run: >-
        python3 -m unittest discover
      env:
        IMS_TOKEN: ${{ secrets.IMS_TOKEN }}

    #- name: Publish package to TestPyPI
    #  uses: pypa/gh-action-pypi-publish@release/v1
    #  with:
    #    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #    repository_url: https://test.pypi.org/legacy/
